- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipeline-conn'
    subscriptionId: '17ec80f8-38b3-4c43-9c8f-e4e8b8496f01'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'PraticaARM'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'CreateWebApp/azuredeploy.json'
    overrideParameters: |
      -projectName arm -linkedTemplateUri 
      https://raw.githubusercontent.com/lfogaca43/arm/master/CreateWebApp/linkedStorageAccount.json
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

    trigger:
    - master

    pool:
      vmImage: 'Ubuntu-latest'

